// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientInformationPortalAPI.Models;

#nullable disable

namespace PatientInformationPortalAPI.Migrations
{
    [DbContext(typeof(PatientInfoContext))]
    [Migration("20240302135603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.Allergies", b =>
                {
                    b.Property<int>("AllergiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergiesID"));

                    b.Property<string>("AllergiesName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AllergiesID");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            AllergiesID = 1,
                            AllergiesName = "Peanuts"
                        },
                        new
                        {
                            AllergiesID = 2,
                            AllergiesName = "Shellfish"
                        },
                        new
                        {
                            AllergiesID = 3,
                            AllergiesName = "Fish"
                        },
                        new
                        {
                            AllergiesID = 4,
                            AllergiesName = "Oniments"
                        },
                        new
                        {
                            AllergiesID = 5,
                            AllergiesName = "Eggs"
                        },
                        new
                        {
                            AllergiesID = 6,
                            AllergiesName = "Tree nuts"
                        },
                        new
                        {
                            AllergiesID = 7,
                            AllergiesName = "Others"
                        },
                        new
                        {
                            AllergiesID = 8,
                            AllergiesName = "No Allergies"
                        });
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.AllergiesDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AllergiesID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AllergiesID");

                    b.HasIndex("PatientID");

                    b.ToTable("Allergies_Details");
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.DiseaseInformation", b =>
                {
                    b.Property<int>("DiseaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseID"));

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DiseaseID");

                    b.ToTable("DiseaseInformation");

                    b.HasData(
                        new
                        {
                            DiseaseID = 1,
                            DiseaseName = "Dengue Fever"
                        },
                        new
                        {
                            DiseaseID = 2,
                            DiseaseName = "Malaria"
                        },
                        new
                        {
                            DiseaseID = 3,
                            DiseaseName = "Typhoid fever"
                        },
                        new
                        {
                            DiseaseID = 4,
                            DiseaseName = "COVID-19"
                        });
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.NCD", b =>
                {
                    b.Property<int>("NCDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCDID"));

                    b.Property<string>("NCDName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("NCDID");

                    b.ToTable("NCD");

                    b.HasData(
                        new
                        {
                            NCDID = 1,
                            NCDName = "Diabetes"
                        },
                        new
                        {
                            NCDID = 2,
                            NCDName = "Hypertension"
                        },
                        new
                        {
                            NCDID = 3,
                            NCDName = "Obesity"
                        },
                        new
                        {
                            NCDID = 4,
                            NCDName = "Asthma"
                        },
                        new
                        {
                            NCDID = 5,
                            NCDName = "Heart Disease"
                        },
                        new
                        {
                            NCDID = 6,
                            NCDName = "Cancer"
                        },
                        new
                        {
                            NCDID = 7,
                            NCDName = "Stroke"
                        },
                        new
                        {
                            NCDID = 8,
                            NCDName = "Chronic Kidney Disease"
                        });
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.NCDDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("NCDID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NCDID");

                    b.HasIndex("PatientID");

                    b.ToTable("NCD_Details");
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.PatientInformation", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<int>("DiseaseID")
                        .HasColumnType("int");

                    b.Property<int>("EpilepsyStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PatientID");

                    b.HasIndex("DiseaseID");

                    b.ToTable("PatientsInformation");
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.AllergiesDetail", b =>
                {
                    b.HasOne("PatientInformationPortalAPI.Models.ContextModels.Allergies", "Allergies")
                        .WithMany()
                        .HasForeignKey("AllergiesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientInformationPortalAPI.Models.ContextModels.PatientInformation", "PatientInformation")
                        .WithMany("AllergiesDetails")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergies");

                    b.Navigation("PatientInformation");
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.NCDDetail", b =>
                {
                    b.HasOne("PatientInformationPortalAPI.Models.ContextModels.NCD", "NCD")
                        .WithMany()
                        .HasForeignKey("NCDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientInformationPortalAPI.Models.ContextModels.PatientInformation", "PatientInformation")
                        .WithMany("NCDDetails")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NCD");

                    b.Navigation("PatientInformation");
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.PatientInformation", b =>
                {
                    b.HasOne("PatientInformationPortalAPI.Models.ContextModels.DiseaseInformation", "DiseaseInformation")
                        .WithMany("PatientInformations")
                        .HasForeignKey("DiseaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiseaseInformation");
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.DiseaseInformation", b =>
                {
                    b.Navigation("PatientInformations");
                });

            modelBuilder.Entity("PatientInformationPortalAPI.Models.ContextModels.PatientInformation", b =>
                {
                    b.Navigation("AllergiesDetails");

                    b.Navigation("NCDDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
